if(NOT INPUTS OR NOT OUTPUT)
    return()
endif()

function(split var size)
    string(LENGTH ${${var}} len)

    set(chunks)
    foreach(i RANGE 0 ${len} ${size})
        string(SUBSTRING ${${var}} ${i} ${size} chunk)
        list(APPEND chunks ${chunk})
    endforeach ()

    set(${var} ${chunks} PARENT_SCOPE)
endfunction()

set(source "/* Generated by Asset.cmake */")

foreach(arg ${INPUTS})
    file(READ "${arg}" data HEX)
    string(LENGTH ${data} size)
    split(data 32)

    string(REGEX REPLACE "[^a-zA-Z0-0_]" "_" arg "${arg}")
    string(PREPEND arg "${PREFIX}")

    string(APPEND source "
    .section .rodata.${arg}, \"a\"
    .balign
    .global ${arg}
${arg}:
    ")

    foreach(line ${data})
        split(line 2)
        list(TRANSFORM line PREPEND "0x")
        list(JOIN line ", " line)

        string(APPEND source ".byte ${line}
    ")
    endforeach()

    math(EXPR size "${size} / 2")

    string(APPEND source "
    .global ${arg}_end
${arg}_end:

    .global ${arg}_size
    .balign 4
${arg}_size: .int ${size}
")
endforeach()

file(WRITE "${OUTPUT}" "${source}")
